//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.ATWService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATWService.ILicensingModule")]
    public interface ILicensingModule {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:uATWLicensingModuleIntf-ILicensingModule) of message RequestLicenseInfoRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uATWLicensingModuleIntf-ILicensingModule#RequestLicenseInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ATM.ATWService.RequestLicenseInfoResponse RequestLicenseInfo(ATM.ATWService.RequestLicenseInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestLicenseInfo", WrapperNamespace="urn:uATWLicensingModuleIntf-ILicensingModule", IsWrapped=true)]
    public partial class RequestLicenseInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] xmlLicense;
        
        public RequestLicenseInfoRequest() {
        }
        
        public RequestLicenseInfoRequest(string[] xmlLicense) {
            this.xmlLicense = xmlLicense;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestLicenseInfoResponse", WrapperNamespace="urn:uATWLicensingModuleIntf-ILicensingModule", IsWrapped=true)]
    public partial class RequestLicenseInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RequestLicenseInfoResponse() {
        }
        
        public RequestLicenseInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILicensingModuleChannel : ATM.ATWService.ILicensingModule, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicensingModuleClient : System.ServiceModel.ClientBase<ATM.ATWService.ILicensingModule>, ATM.ATWService.ILicensingModule {
        
        public LicensingModuleClient() {
        }
        
        public LicensingModuleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicensingModuleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicensingModuleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicensingModuleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATM.ATWService.RequestLicenseInfoResponse ATM.ATWService.ILicensingModule.RequestLicenseInfo(ATM.ATWService.RequestLicenseInfoRequest request) {
            return base.Channel.RequestLicenseInfo(request);
        }
        
        public string RequestLicenseInfo(string[] xmlLicense) {
            ATM.ATWService.RequestLicenseInfoRequest inValue = new ATM.ATWService.RequestLicenseInfoRequest();
            inValue.xmlLicense = xmlLicense;
            ATM.ATWService.RequestLicenseInfoResponse retVal = ((ATM.ATWService.ILicensingModule)(this)).RequestLicenseInfo(inValue);
            return retVal.@return;
        }
    }
}
